exception 'Exception' with message 'The my exception' in D:\Web\nette\_trunk\tests\Debug\test.exception.php:29
Stack trace:
#0 D:\Web\nette\_trunk\tests\Debug\test.exception.php(23): third(Array)
#1 D:\Web\nette\_trunk\tests\Debug\test.exception.php(16): second(true, false)
#2 D:\Web\nette\_trunk\tests\Debug\test.exception.php(33): first(10, 'any string')
#3 {main}
PHP 5.2.8
Nette Framework 0.8 (revision $WCREV$ released on $WCDATE$)
Report generated at 01/23/08 00:00:00
