exception 'FatalErrorException' with message 'Error generated by trigger_error' in D:\Web\nette\_trunk\tests\Debug\test.error.php:29
Stack trace:
#0 D:\Web\nette\_trunk\tests\Debug\test.error.php(29): trigger_error('Error generated...', 256)
#1 D:\Web\nette\_trunk\tests\Debug\test.error.php(23): third(Array)
#2 D:\Web\nette\_trunk\tests\Debug\test.error.php(16): second(true, false)
#3 D:\Web\nette\_trunk\tests\Debug\test.error.php(33): first(10, 'any string')
#4 {main}
PHP version 5.2.6
Nette Framework version 0.7
Report generated at 01/23/08 00:00:00
