<h1>Nette::Debug recoverable error test</h1>


<pre>
Invalid argument #1
exception 'InvalidArgumentException' with message 'Argument 1 passed to TestClass::test1() must be an array, string given, called in D:\Web\nette\_trunk\tests\Debug\test.recoverable.php on line 40 and defined' in D:\Web\nette\_trunk\tests\Debug\test.recoverable.php:17
Stack trace:
#0 D:\Web\nette\_trunk\tests\Debug\test.recoverable.php(40): TestClass->test1('hello')
#1 {main}

Invalid argument #2
exception 'InvalidArgumentException' with message 'Argument 1 passed to TestClass::test2() must be an instance of TestClass, string given, called in D:\Web\nette\_trunk\tests\Debug\test.recoverable.php on line 47 and defined' in D:\Web\nette\_trunk\tests\Debug\test.recoverable.php:22
Stack trace:
#0 D:\Web\nette\_trunk\tests\Debug\test.recoverable.php(47): TestClass->test2('hello')
#1 {main}

Invalid toString
exception 'FatalErrorException' with message 'Method TestClass::__toString() must return a string value' in D:\Web\nette\_trunk\tests\Debug\test.recoverable.php:54
Stack trace:
#0 {main}

